#!/usr/bin/env php
<?php
/**
 * @author czz
 */

function index()
{
    $table_name = 'nice_xz_car';
    $dir_name = 'xz';
    $TableName = convertUnderline($table_name);

    // 生成model文件
    $tpl_model = file_get_contents('./tpl/tpl_model.php');
    $tpl_model = str_replace('DATE_TIME', date("Y-m-d H:i"), $tpl_model);
    $tpl_model = str_replace('MODEL_NAME', $TableName, $tpl_model);
    $tpl_model = str_replace('TABLE_NAME', $table_name, $tpl_model);

    // 生成controller文件
    $tpl_controller = file_get_contents('./tpl/tpl_controller.php');
    $tpl_controller = str_replace(
        'DATE_TIME', date("Y-m-d H:i"), $tpl_controller
    );
    $tpl_controller = str_replace('CONTROLLER_NAME', $TableName, $tpl_controller);
    $tpl_controller = str_replace('TABLE_NAME', $table_name, $tpl_controller);
    $tpl_controller = str_replace('DIR_NAME', $dir_name, $tpl_controller);
    $tpl_controller = str_replace('MODEL_NAME', $TableName, $tpl_controller);

    if (!is_dir('generate_file')) {
        if (!mkdir('./generate_file', 0777, 1)) {
            echo "创建目录失败"; exit;
        }
    }

    if (!is_dir('generate_file/'.$table_name)) {
        if (!mkdir('./generate_file/'.$table_name, 0777, 1)) {
            echo "创建目录失败"; exit;
        }
    }

    file_put_contents('./generate_file/'.$table_name . "/" .$TableName . '_model.php', $tpl_model);
    echo "生成model文件-------" . $table_name . "/" .$TableName . '_model.php';
    echo PHP_EOL;

    file_put_contents('./generate_file/'.$table_name . "/" .$TableName . '.php', $tpl_controller);
    echo "生成controller文件-------" . $table_name . "/" .$TableName . '.php';
    exit;
}

function convertUnderline($str, $search = 'nice')
{
    $str = preg_replace_callback(
        '/([-_]+([a-z]{1}))/i', function($matches) {
        return strtoupper($matches[2]);
    }, $str
    );

    return str_replace($search, '', $str);
}

index();
