#!/usr/bin/env php
<?php
/**
 * @author czz
 */



function index()
{
    $table_name = 'nice_crm2_campus';
    $dir_name = 'mcrm';
    $TableName = convertUnderline($table_name);
    $DATABASE_FILED1 = printMd($table_name,1);
    $DATABASE_FILED2 = printMd($table_name,2);

    // 生成查询接口文档
    $list_md = file_get_contents('./tpl/list.md');
    $list_md = str_replace('CONTROLLER_NAME', $TableName, $list_md);
    $list_md = str_replace('DIR_NAME', $dir_name, $list_md);
    $list_md = str_replace('DATABASE_FILED1', $DATABASE_FILED1, $list_md);
    $list_md = str_replace('DATABASE_FILED2', $DATABASE_FILED2, $list_md);

    // 生成编辑操作接口文档
    $edit_md = file_get_contents('./tpl/edit.md');
    $edit_md = str_replace('CONTROLLER_NAME', $TableName, $edit_md);
    $edit_md = str_replace('DIR_NAME', $dir_name, $edit_md);
    $edit_md = str_replace('DATABASE_FILED1', $DATABASE_FILED1, $edit_md);

    // 生成新增操作接口文档
    $add_md = file_get_contents('./tpl/add.md');
    $add_md = str_replace('CONTROLLER_NAME', $TableName, $add_md);
    $add_md = str_replace('DIR_NAME', $dir_name, $add_md);
    $add_md = str_replace('DATABASE_FILED1', $DATABASE_FILED1, $add_md);

    // 生成新增操作接口文档
    $del_md = file_get_contents('./tpl/del.md');
    $del_md = str_replace('CONTROLLER_NAME', $TableName, $del_md);
    $del_md = str_replace('DIR_NAME', $dir_name, $del_md);

    if (!is_dir('generate_doc')) {
        if (!mkdir('./generate_doc', 0777, 1)) {
            echo "创建目录失败"; exit;
        }
    }

    if (!is_dir('generate_doc/'.$table_name)) {
        if (!mkdir('./generate_doc/'.$table_name, 0777, 1)) {
            echo "创建目录失败"; exit;
        }
    }

    file_put_contents("./generate_doc/{$table_name}/".$table_name. '_list.md', $list_md);
    echo "生成查询列表接口文档文件-------" . $table_name . '_list.md';
    echo PHP_EOL;

    file_put_contents("./generate_doc/{$table_name}/".$table_name. '_edit.md', $edit_md);
    echo "生成编辑操作接口文档文件-------" . $table_name . '_edit.md';
    echo PHP_EOL;

    file_put_contents("./generate_doc/{$table_name}/".$table_name. '_add.md', $add_md);
    echo "生成添加操作接口文档文件-------" . $table_name . '_add.md';
    echo PHP_EOL;

    file_put_contents("./generate_doc/{$table_name}/".$table_name. '_del.md', $del_md);
    echo "生成删除操作接口文档文件-------" . $table_name . '_del.md';
    echo PHP_EOL;
}


function excute_sql($sql)
{
    $dbconfig = [
        'host' => '127.0.0.1',
        'port' => '5432',
        'dbname' => 'db1',
        'user' => 'postgres',
        'password' => 'password',
    ];

    $conn_string = "host={$dbconfig['host']} port={$dbconfig['port']} dbname={$dbconfig['dbname']} user={$dbconfig['user']} password={$dbconfig['password']}";
    $conn = pg_connect($conn_string) or die("Could not connect");

    $result = pg_query($conn, $sql);
    $rs = pg_fetch_all($result);

    pg_close($conn);

    return $rs;
}

// 表结构和字段注释
function tableDesc($table = '') {

    $sql = "SELECT A .attnum,
	        (
      		  SELECT description FROM pg_catalog.pg_description
		      WHERE objoid = A .attrelid AND objsubid = A .attnum
        	) AS description, A .attname, pg_catalog.format_type (A .atttypid, A .atttypmod) AS data_type
            FROM pg_catalog.pg_attribute A
            WHERE 1 = 1 AND A .attrelid = (SELECT oid FROM pg_class	WHERE relname = '{$table}')
            AND A .attnum > 0 AND NOT A .attisdropped
            ORDER BY A .attnum;";

    return excute_sql($sql);
}

/**
 * @param     $table 表名
 * @param int $type  1打印出是否必选 2不打印出是否必选
 *
 * @return string
 */
function printMd($table, $type = 1) {
    if (empty($table)) {return '';}

    $fileds = tableDesc($table);

    if ($type == 1) {
        $html = "|参数名|必选|类型|说明|";
        $html .= PHP_EOL;
        $html .= "|:----|:---|:----- |-----|";

        foreach ($fileds as $v) {
            $html .= PHP_EOL;
            $html .= "| ".$v['attname']." | 否 | ".$v['data_type']." | {$v['description']} |";
        }
    }

    if ($type == 2) {
        $html = "|字段名|类型|说明|";
        $html .= PHP_EOL;
        $html .= "|:----|:----- |-----|";

        foreach ($fileds as $v) {
            $html .= PHP_EOL;
            $html .= "| ".$v['attname']." | ".$v['data_type']." | {$v['description']} |";
        }
    }

    return $html;
}

function convertUnderline($str, $search = 'nice')
{
    $str = preg_replace_callback(
        '/([-_]+([a-z]{1}))/i', function($matches) {
        return strtoupper($matches[2]);
    }, $str
    );

    return str_replace($search, '', $str);
}

index();
