-- czz DATE_TIME
-- TABLE_DESC
DROP TABLE IF EXISTS public.TABLE_NAME;
DROP SEQUENCE IF EXISTS public.TABLE_NAME_id_seq;

CREATE SEQUENCE TABLE_NAME_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE TABLE_NAME(
    id INTEGER NOT NULL DEFAULT nextval('TABLE_NAME_id_seq'::regclass),
    cuid int4 DEFAULT 0 NOT NULL,
    ctime int4 DEFAULT 0 NOT NULL,
    muid int4 DEFAULT 0 NOT NULL,
    mtime int4 DEFAULT 0 NOT NULL
);

COMMENT ON TABLE "public"."TABLE_NAME" IS 'TABLE_DESC';
COMMENT ON COLUMN "public"."TABLE_NAME"."id" IS 'id';
COMMENT ON COLUMN "public"."TABLE_NAME"."ctime" IS '创建时间';
COMMENT ON COLUMN "public"."TABLE_NAME"."cuid" IS '创建者';
COMMENT ON COLUMN "public"."TABLE_NAME"."mtime" IS '修改时间';
COMMENT ON COLUMN "public"."TABLE_NAME"."muid" IS '修改者';

ALTER TABLE ONLY TABLE_NAME ADD CONSTRAINT TABLE_NAME_pkey PRIMARY KEY (id);
